### ISSUE TITLE
Make clippy happy

### ISSUE THREAD

**Issue by behnam** [llogiq/flamer#20]
Value returned by functions that return unit type get assigned to a variable by flamer, which makes clippy unhappy.

```
warning: this let-binding has unit value. Consider omitting `let flame) =`
  --> src/explicit.rs:23:34
   |
23 | #[cfg_attr(feature = "flame_it", flame)]
   |                                  ^^^^^^
   |
   = note: #[warn(let_unit_value)] on by default
   = help: for further information visit https://github.com/Manishearth/rust-clippy/wiki#let_unit_value
```

It's a low-pri issue, but something to track and nice to fix at some point.

**Comment by llogiq** [comment]
Flamer now uses the flame_guard API so we thankfully no longer run into this problem.
