### ISSUE TITLE
Add a travis CI nightly build

### ISSUE THREAD

**Issue by joelgallant** [llogiq/flamer#35]
Since flamer uses nightly APIs, and does break every so often when upstream does, might be nice for the "build passing" badge to indicate correctly whether the library compiles with the latest nightly build?

I don't mean to sound like there's an obligation to update the library every day it breaks, just helps passerbyers.

See: https://docs.travis-ci.com/user/cron-jobs

**Comment by llogiq** [comment]
Good idea. I will set up a job when I get to my PC.

**Comment by joelgallant** [comment]
Looks like this is set up now
